Moving logic to only create the drop in the end
holaplex/drops-dashboard pull request #11
Opened 2022-07-22 14:32 UTC by Plucks77

2022-07-26 21:07 UTC, fc-anjos requested changes

2022-07-26 21:07 UTC, fc-anjos commented on backend/app/controllers/nft_controller.rb
>        i += 2
Are we iterating every other row? Look into `.each_slice(2)`.

Anyway, this tabs iteration could be its own method, there's a lot of logic going on here. Extracting what should be done for each nft in a method, filtering first or iterating over what's needed will be cleaner

2022-07-26 21:07 UTC, fc-anjos commented on backend/app/models/nft.rb
>      pp 'FIELDS', fields
remove pp

2022-07-26 21:07 UTC, fc-anjos commented on backend/app/models/nft.rb
> +  def do_watermark(src, dst, watermark = './app/assets/images/watermark-45.png')
"Do" and "Make" watermark seem like confusing names

2022-07-26 21:28 UTC, fc-anjos commented
Hey @umschaudhary,

there are a bunch of additions here that seem like linter changes:
Switching " to ' and adding ;
or:

```
-    File.exists?(self.watermark_filename)
+    File.exist?(watermark_filename)
```

We all need to connect on this, make sure we're using the same linter configuration, open a single PR to lint it all and not having it spread across a lot of small changes. Makes it much harder to review.
@Plucks77 @thenifemi @jonathastavares

2022-07-27 13:47 UTC, umschaudhary commented on backend/app/models/nft.rb
> +  def do_watermark(src, dst, watermark = './app/assets/images/watermark-45.png')
These are commented out since not used anywhere

2022-07-27 13:47 UTC, umschaudhary commented on backend/app/controllers/nft_controller.rb
>        i += 2
segregated logic to seperate methods

2022-07-27 13:48 UTC, umschaudhary commented on backend/app/controllers/nft_controller.rb
> +  require 'securerandom'
removed

2022-07-29 19:00 UTC, fc-anjos requested changes

2022-07-29 19:00 UTC, fc-anjos commented on backend/app/services/nft_service.rb
> +        (8..last).each do |i| # 8th row is a starting row
Almost there! Let's filter for nil first, and then map the nfts. We don't need this empty array as a sidecar

2022-08-01 12:11 UTC, fc-anjos approved these changes

2022-08-01 12:12 UTC, merged